import type { Metadata } from "next"
import "./globals.css"
import { inter, nunito } from "./utils/fonts"

export const metadata: Metadata = {
  title: "Dr. Matheus Wasem",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="pt-br">
      <body
        style={{ scrollBehavior: "smooth" }}
        className={`${inter} ${nunito} antialiased scroll-smooth`}
      >
        {children}
      </body>
    </html>
  )
}
